# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019 University of Zurich.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# should GC3Pie autodiscover resource features? (only on localhost)
tm_compute_autodiscover: yes

# total number of nodes in the cluster
tm_compute_nodes: "{{ groups.tissuemaps_compute|length|default(1) }}"

# usable number of CPU cores per node, defaults to all available cores
tm_compute_cores:  "{{ansible_processor_vcpus}}"

# usable memory of a node, defaults to 80% of node memory
tm_compute_memory: "{{ (ansible_memtotal_mb * 80 / 100) |int }}"

# FIXME: should this be raised? DB scans for large experiments take even more...
uwsgi_timeout: 300

# Github user names of administrators
tm_admins: []

# contact data for the database server
#
# FIXME: I'm not sure it makes much sense to go through hoops just to
# have connections go to `localhost` or a UNIX-domain socket; this
# only applies to the master, the real data connections are to the
# workers, which are always contacted via TCP...
#
app_host: "{{ hostvars[inventory_hostname].ansible_host }}"
tm_db_host: "{{ db_host_master if db_host_master != app_host else 'localhost' }}"
