# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016, 2018, 2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
cluster_mode: no

matlab_version: '2016b'

# NOTE: Make sure this matches the PostgreSQL version provided by Citus
# (see ../database-server-common/defaults/main.yml)
postgresql_version: '11'

storage_directory: /storage


tm_repo_url: https://github.com/TissueMAPS/TissueMAPS
tm_version: master

tm_user: tissuemaps
tm_group: "{{ tm_user }}"

# user account to populate the DB with; array of mappings with keys
# "name", "password" and "email"
tm_users: []


# connection parameters of DB master and workers
db_host_master: "{{ hostvars[groups.tissuemaps_db_master[0]].ansible_host }}"
db_port_master: 5432

db_hosts_workers: "{{ groups.tissuemaps_db_worker|map('extract', hostvars, ['ansible_host'])|list }}"
db_port_worker: 9700

# PostGreSQL DB auth parameters
db_user: postgres
db_group: "{{ db_user }}"
db_role: tissuemaps
db_name: tissuemaps

# number of worker nodes in the cluster
db_nodes: "{{ db_host_workers|length|default(1)|int }}"
