# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016, 2018  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Update ``db_host`` in TissueMAPS configuration
  ini_file:
    dest: "{{ tm_config_file }}"
    section: DEFAULT
    state: present
    option: db_host
    value: "{{ db_host_master if db_host_master != client_host else 'localhost' }}"
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
  tags:
    - database
    - tissuemaps

- name: Update ``db_nodes`` in TissueMAPS configuration
  ini_file:
    dest: "{{ tm_config_file }}"
    section: DEFAULT
    state: present
    option: db_nodes
    value: "{{ db_nodes }}"
    owner: "{{ tm_user }}"
    mode: "u+rwx"
  tags:
    - tissuemaps

- name: Update value of TMAPS_DB_HOST
  lineinfile:
    dest: "{{ tm_home }}/.bash_profile"
    line: "export TMAPS_DB_HOST={{ db_host_master if db_host_master != client_host else 'localhost' }}"
    regexp: "^export.TMAPS_DB_HOST.*"
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
  with_items:
    - "{{ tm_home }}/.bash_profile"
    - "{{ tm_home }}/.tmaps/uwsgi.sh"
  tags:
    - database
    - tissuemaps
