#!/usr/bin/env python
import logging
from tmlib.cli import command_line_call
from tmlib.illuminati.argparser import parser

logger = logging.getLogger(__name__)


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    command_line_call(parser)
