- name: Check for a `requirements.txt` file in `{{ pkg_dir }}`
  stat:
    path: '{{ pkg_dir }}/requirements.txt'
    get_checksum: no
    mime: no
  register: _install_python_pkg_has_requirements_txt


- name: 'Install Python package requirements from `{{ pkg_dir }}/requirements.txt`'
  shell: |
    env PYTHONUSERBASE='{{ tm_home }}/.local' \
        pip install --user --no-cache-dir -r 'requirements.txt'
  args:
    chdir: "{{ pkg_dir }}"
  when: '_install_python_pkg_has_requirements_txt.stat.exists'


- name: 'Install Python package from `{{ pkg_dir }}`'
  shell: |
    env PYTHONUSERBASE='{{ tm_home }}/.local' \
        pip install --user --no-cache-dir '{{ pkg_dir }}'
  args:
    chdir: "{{ pkg_dir }}"
