# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019 University of Zurich.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

- name: Install apt packages required for Python
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-pip
    - python-tk
    - python-setuptools
    - libssl-dev
    - libffi-dev
  tags:
    - python

- name: Install apt packages required by Python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libopenblas-dev
    # gc3pie:
    - time
    # h5py:
    - libhdf5-dev
    - hdf5-tools
    # lxml:
    - libxml2-dev
    - libxslt1-dev
    # matplotlib: TODO: are the GUI dependencies really necessary?
    - pyqt4-dev-tools
    - libfreetype6-dev
    - python-tk
    # shapely:
    - libgeos-dev
  tags:
    - python
