# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2019  University of Zurich
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Deploy NginX configuration and startup script
  template:
    src: 'nginx.conf.j2'
    dest: '/home/{{ tm_user }}/.tmaps/nginx.conf'
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 'ug+r,o-rwx'
  tags:
    - app-server
    - uwsgi


- name: Install NginX
  package:
    name:
      - nginx
    state: present


- name: Disable system-level NginX startup
  service:
    name: nginx
    state: stopped
    enabled: no
  when: 'web_port|int in [80, 443]'
