---
- name: Common setup for all hosts
  hosts: all
  gather_facts: yes
  any_errors_fatal: yes
  roles:
    - role: common
    - role: iptables
      # FIXME: should change to 'DROP' when all playbooks register their input ports!
      default_input_policy: 'ACCEPT'
    - role: ntpd
      ntp_server: '{{groups.ntp_master|default([])}}'
    - role: pdsh

# Run all other playbooks one by one, so they get a chance of doing
# their setup depending on configured host groups
- import_playbook: roles/slurm.yml

- import_playbook: roles/ganglia.yml

- import_playbook: roles/glusterfs.yml
