---

# Ansible uses `usermod`, which is not able to modify NIS-based
# records, so skip creation of user and group if they are not local to
# /etc/passwd

- name: Does the TM system group exist yet?
  command: |
    getent group {{ tm_group }}
  ignore_errors: yes
  register: _tm_group_exists

- name: Create TM system group
  group:
    name: '{{ tm_user }}'
    system: yes
    state: present
  when: _tm_group_exists is failed

- name: Does the TM system user exist yet?
  command: |
    getent passwd {{ tm_group }}
  ignore_errors: yes
  register: _tm_user_exists

- name: Create TM system user
  user:
    name: '{{ tm_user }}'
    group: '{{ tm_user }}'
    home: '{{ tm_user_home }}'
    comment: "System user for running TissueMAPS services"
    system: yes
    state: present
  when: _tm_user_exists is failed

- name: Ensure `~/.ssh` directory exists
  file:
    path: '{{ tm_user_home }}/.ssh'
    owner: '{{ tm_user }}'
    group: '{{ tm_user }}'
    mode: 0755
    state: directory

- name: Deploy SSH keys of authorized users
  tags:
    - tissuemaps
    - ssh
  authorized_key:
    user: "{{ tm_user }}"
    key: https://github.com/{{ item }}.keys
  loop: "{{ tm_admins }}"
  when: ansible_env.ANSIBLE_CONTAINER is undefined

- name: Allow tm_user to control TM services
  become: yes
  template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers.d/tissuemaps'
    owner: root
    group: root
    mode: 0440
