# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2018  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Download Citus install script
  get_url:
    url: 'https://install.citusdata.com/community/rpm.sh'
    dest: '{{ tm_home }}/citus.sh'
    mode: 0755
  tags:
    - database

- name: Add Citus repository
  command: "{{ tm_home }}/citus.sh"
  args:
    creates: /etc/yum.repos.d/citusdata_community.repo
  tags:
    - database

- name: Install apt packages required by Citus PostgreSQL
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - citus{{ citus_version | regex_replace('(\.)', '') }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - postgresql{{ postgresql_version | regex_replace('(\.)', '') }}-contrib
    - postgis{{ postgis_version[0] }}_{{ postgresql_version | regex_replace('(\.)', '') }}
    - python-psycopg2
  tags:
    - database

- name: Install setfacl support
  package:
    name: acl
  tags:
    - database

- name: Set directory paths for PostgreSQL executables
  set_fact:
    db_executable_directory: /usr/pgsql-{{ postgresql_version }}/bin
    db_default_cluster_data_directory: /var/lib/pgsql-{{ postgresql_version }}/data
  tags:
    - database
