# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Download Citus install script
  get_url:
    url: 'https://install.citusdata.com/community/deb.sh'
    dest: '{{ tm_home }}/citus.sh'
    mode: 0755
  tags:
    - database

- name: Add Citus repository
  command: "{{ tm_home }}/citus.sh"
  args:
    creates: /etc/apt/sources.list.d/citusdata_community.list
  tags:
    - database

- name: Install apt packages required by Citus PostgreSQL
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - postgresql-{{ postgresql_version }}-citus-{{ citus_version }}
    - postgis
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-server-dev-all
    - python-psycopg2
  tags:
    - database

- name: Install setfacl support
  apt:
    name: acl
  tags:
    - database

- name: Set directory paths for PostgreSQL executables
  set_fact:
    db_executable_directory: /usr/lib/postgresql/{{ postgresql_version }}/bin
    db_default_cluster_data_directory: /var/lib/postgresql/{{ postgresql_version }}/main
  tags:
    - database
