# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- include_tasks: install-{{ ansible_os_family }}.yml

- import_tasks: data_dir.yml

- import_tasks: create_cluster.yml

- import_tasks: configure.yml

- name: Start database cluster
  tags:
    - database
  command: |
    {{ db_executable_directory }}/pg_ctl start -w -o "-p {{ db_port }}" -D {{ db_data_directory }}/{{ db_node }} -l {{ db_log_directory }}/postgresql-{{ db_node }}.log
  args:
    chdir: "{{ db_data_directory }}"
  become: yes
  become_user: '{{ db_user }}'

- import_tasks: create_database.yml

- import_tasks: create_users.yml

- name: Stop database cluster
  tags:
    - database
  command: |
    {{ db_executable_directory }}/pg_ctl stop -w -m smart -o "-p {{ db_port }}" -D {{ db_data_directory }}/{{ db_node }}
  args:
    chdir: "{{ db_data_directory }}"
  become: yes
  become_user: '{{ db_user }}'
